### ISSUE TITLE
Problem with building the website

### ISSUE THREAD

**Issue by LeyiCui-Angel** [COMS-BC3997-SP23/website-LeyiCui-Angel#3]
Fail in Actions that I couldn't figure out

Error: The process '/opt/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle' failed with exit code 5

**Comment by plancherb1** [comment]
When you did a merge you left in this line here which is breaking your build! https://github.com/COMS-BC3997-SP23/website-LeyiCui-Angel/blob/main/_config.yml#L181

Also you may want to delete and remove the gemfile.lock from the repo as that was also breaking things on my end -- you'll always generate one locally but you can choose not to add it to your repo by creating a `.gitignore` file e.g., https://github.com/COMS-BC3997-SP23/COMS-BC3997-SP23.github.io/blob/main/.gitignore
See here for what commands to run to get that new file to take effect https://stackoverflow.com/questions/1274057/how-do-i-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by LeyiCui-Angel** [comment]
Hi Brian I deleted the line and also the gemfile.lock file. However, it's still failing in building...

Error: The process '/opt/hostedtoolcache/Ruby/3.0.5/x64/bin/bundle' failed with exit code 6

**Comment by LeyiCui-Angel** [comment]
Rebuild the website
